# Theme
remote_theme: "mmistakes/minimal-mistakes@4.16.5"
minimal_mistakes_skin: "dark"

# Site Settings
title: AsterLinux
description: AsterLinux Project Development
subtitle: AsterLinux Github
name: Aster Linux
url: "https://asterlinuxdev.github.io"
repository: "asterlinuxdev/asterlinuxdev.github.io"
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/

#logo: "/assets/images/aster-logo.png"

# Site Author
author:
  name: "Aster Linux"
  avatar: "/assets/images/aster-logo256.png"
  bio: "Home of the AsterLinux Project"
  location: "United Kingdom"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/asterlinuxdev"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/asterlinuxdev"

# reading files
include:
  - _pages

exclude: [vendor]

plugins:
  - jekyll-include-cache
  - jekyll-feed

# defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _portfolio
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: false
      share: true

collections:
  project:
    output: true
    permalink: /:collection/:path/