remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

  logo: "/assets/images/asterlinux-logo1.png"

  # Site Settings
title: AsterLinux Github
description: Home of the AsterLinux Project
subtitle: AsterLinux Development Github
name: AsterLinux Github Repository
url: "https://asterlinuxdev.github.io"
repository: "asterlinuxdev/asterlinuxdev.github.io"
paginate: 5 # amount of posts to show
paginate_path: /page:num/

# Site Author
author:
  name: "AsterLinux"
  avatar: "/assets/images/asterlinux-logo1.png"
  bio: "Home of the AsterLinux Project"
  location: "United Kingdom"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/asterlinuxdev"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/asterlinuxdev"

# reading files
include:
  - ["_pages"]

exclude: [vendor]

# defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true